<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    Total result: <?= number_format($total, 0, '.','.'); ?>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <?php if($this->can_i->create_banner): ?>
                <a class="btn btn-primary pull-right" href="<?= $this->router->to('adminBannerEdit', ['id'=>0], ['ref'=>$reff]) ?>">Create New</a>
                <?php endif; ?>
                <h3>Banners</h3>
            </div>
            
            <?php if($banners): ?>
            <?php
                $can_delete     = $this->can_i->remove_banner;
                $can_edit       = $this->can_i->update_banner;
            ?>
            
            <div class="list-group">
                <?php foreach($banners as $banner): ?>
                    <?php $expired = time() > strtotime($banner->expired); ?>
                <div class="list-group-item<?= ($expired ? ' list-group-item-warning' : '') ?>">
                    
                    <?php if($can_edit || $can_delete): ?>
                    <div class="btn-group btn-group-xs pull-right" role="group">
                        
                        <?php if($can_edit): ?>
                        <a href="<?= $this->router->to('adminBannerEdit', ['id'=>$banner->id], ['ref'=>$reff]) ?>" class="btn btn-default" title="Edit">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                        <?php endif; ?>
                        
                        <?php if($can_delete): ?>
                        <button id="banner-<?= $banner->id ?>" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-default btn-xs">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="banner-<?= $banner->id ?>">
                            <li>
                                <a href="<?= $this->router->to('adminBannerRemove', ['id'=>$banner->id], ['ref'=>$reff]) ?>" data-confirm="Delete Confirmation" data-confirm-message="Are you sure want to delete this banner? This action can't be undone." title="Delete" aria-label="Delete">
                                    <i class="fa fa-trash" aria-hidden="true"></i> Delete
                                </a>
                            </li>
                        </ul>
                        <?php endif; ?>
                        
                    </div>
                    <?php endif; ?>
                    
                    <h4 class="list-group-item-heading"><?= $banner->name ?> <small><?= $banner->placement ?></small></h4>
                    <p class="list-group-item-text small">
                        <span title="Created"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i> <?= date('M d, Y', strtotime($banner->created)) ?></span>
                        &middot;
                        <span title="Expired"><i class="fa fa-calendar-minus-o" aria-hidden="true"></i> <?= date('M d, Y', strtotime($banner->expired)) ?></span>
                    </p>
                </div>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>